# Generated by Django 2.0.4 on 2018-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(blank=True, upload_to='media_cdn/'),
        ),
    ]
