# Generated by Django 2.0.4 on 2018-04-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-completion_date',)},
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table='project_images_new',
        ),
    ]
