# Generated by Django 2.0.4 on 2018-04-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180422_1948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homepage',
            table=None,
        ),
    ]
