# Generated by Django 2.0.4 on 2018-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180422_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(blank=True)),
                ('subhead', models.TextField(blank=True)),
                ('backimage', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
