# Generated by Django 2.0.4 on 2018-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='name',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
