# Generated by Django 2.0.4 on 2018-04-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20180423_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bodyleftabout',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='board',
            name='bodyrightabout',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='board',
            name='headlineabout',
            field=models.CharField(default=123432, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='headlineleftabout',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='board',
            name='headlinerightabout',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='board',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='subheadabout',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
