# Generated by Django 2.0.4 on 2018-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20180423_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imagebns1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='imagebns2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='imagebns3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='imagebns4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionbnsbody',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionbnsheadline',
            field=models.CharField(default=12312424, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='sectionbnssubhead',
            field=models.CharField(default=13443, max_length=250),
            preserve_default=False,
        ),
    ]
