# Generated by Django 2.0.4 on 2018-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20180423_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='sectionbnscellular',
            field=models.CharField(default=2134425, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='sectionbnswireless',
            field=models.CharField(default=42145322, max_length=250),
            preserve_default=False,
        ),
    ]
