# Generated by Django 2.0.4 on 2018-04-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20180423_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imageridr1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='imageridr2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='imageridr3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='imageridr4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr1head',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr2head',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr3head',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridr4head',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridrheadline',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='board',
            name='sectionridrsubhead',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
