# Generated by Django 2.0.4 on 2018-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20180423_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='sectionnoc1',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
