# Generated by Django 2.0.4 on 2018-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20180423_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='sectionnoc2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='board',
            name='sectionnoc3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='board',
            name='sectionnoc4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
