# Generated by Django 2.0.4 on 2018-04-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20180423_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='name',
            new_name='productname',
        ),
    ]
