# Generated by Django 2.0.4 on 2018-04-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_auto_20180423_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='productname',
            new_name='name',
        ),
    ]
