# Generated by Django 2.0.4 on 2018-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_auto_20180424_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='tbipartnumber',
        ),
    ]
