# Generated by Django 2.0.4 on 2018-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tbipartnumber',
            field=models.TextField(max_length=1000),
        ),
    ]
