# Generated by Django 2.0.4 on 2018-04-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_auto_20180424_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image1',
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(default=412, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='companyname',
            field=models.CharField(default=124, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='images',
            field=models.ForeignKey(default=4121, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boards.ProductImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='proddescription',
            field=models.TextField(default=14244, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='productid',
            field=models.CharField(default=411331, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='searchkeys',
            field=models.CharField(default=43111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='subcategory',
            field=models.CharField(default=4314314131, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.CharField(default=1341414141, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='tbipartnumber',
            field=models.TextField(default=13444113, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='value',
            field=models.CharField(default=4313131, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boards.ProductImages'),
        ),
    ]
